### ISSUE TITLE
Support import of spreadsheets

### ISSUE THREAD

**Issue by MartinKl** [korpling/annatto#53]
Annotations provided as Spreadsheet files should be supported as well. This is a more complex issue, since integrating external python libraries failed so far (`openpyxl` would be a great candidate) and the state of libraries for rust for reading purposes seem to mostly in `dev` state.

**Comment by thomaskrause** [comment]
The  `umya-spreadsheet`  crate also supports merged cells similarly to openpyxl: <https://docs.rs/umya-spreadsheet/latest/umya_spreadsheet/structs/struct.Worksheet.html#method.add_merge_cells>
We should check if the crate works good enough on our data, maybe by writing a small test program, before dismissing this option. Considering the "dev" state, we should have a good range of Excel files to test against in case the API has a breaking change, and we need to adapt to the new API without breaking things. These low version numbers indicate that they did not settle on an API yet, but does not say anything about the maturity of the code base (tests and documentation would be more important here). 

If things work with the current version, the main reason to upgrade are security concern in case of a bug or a missing feature. The latter is not a problem if we can read all the files we need already with the current version.

**Comment by thomaskrause** [comment]
For ODS files there is also <https://crates.io/crates/spreadsheet-ods> which seems to support merged cells/spans.
Maybe we just convert every Excel file to ODS using the LibreOffice command line :smile:

**Comment by MartinKl** [comment]
I don't remember why I originally discarded `umya-spreadsheet`, so I will just give it a try. In parallel I will continue trying to make it work embedding `openpyxl` into rust and using the python lane. Converting spreadsheets to ODS is not my favoured solution, considering most projects usually work with `xlsx` anyway and an extra step beforehand makes the whole thing less attractive and more vulnerable in my eyes.
