### ISSUE TITLE
Imports: Report failing documents at the end

### ISSUE THREAD

**Issue by MartinKl** [korpling/annatto#89]
Right now a document with errors causes most import modules to fail immediately. This way, the user will only know about the first document with errors. Especially for large corpora this will be a quite frustrating experience.

The better solution would be to collect documents with errors and report all errors when finishing the import process.

**Comment by thomaskrause** [comment]
This assumes that all imports can be partitioned into documents, which is not always the case. I would not make this a feature of the Annatto pipeline execution, but rather a behavior of each importer.

 If an importer works on documents it can decide to collect the errors internally and then bail out at the end. This would not help with errors that occur later on in the process, e.g. during merge, but would still be better than errors in larger corpora where multiple attempts to fixing the imports would be necessary.

**Comment by MartinKl** [comment]
This is actually a more complex issue:

Currently the code does cannot deal with import_corpus returning an error (workflow breaks, might be an easy fix). This is not the core problem, the question is: How do we actually want to deal with errors: Do we throw errors or do we send `StatusMessage::Failed` while returning `Ok`? I think we want to do the latter, no big deal. That means we do not throw any errors directly and wait for the evaluation of the receiver in the end. This has two problems, though:

+ for large corpora, we learn about issues in the end, i. e. we wait a while to be disappointed (which might still be better than multiple runs to fix errors in many docs one by one)
+ we need to fix (and should!) `annatto-cli.rs::37-41`:

```
for status_update in rx {
        match status_update {
            StatusMessage::Failed(e) => {
                return Err(e);
            }
```

Currently we only learn about one of the many errors that might have occured. And for this it doesn't matter if the import module is document-based or not. Dealing with multiple formats we should also learn about all issues immediately.

What do you think?
